### PR TITLE
Add new columns to ContainerQueueSample and DataCollection

### PR DESCRIPTION
**Pull request by KarlLevik**
- New column to allowing queuing of samples as the ContainerQueueSample table currently only supports subsamples
- New column to link a ContainerQueueSample to DataCollectionPlan to give us the queued collection parameters for the sample
- New column to link DataCollection to DataCollectionPlan so we see the requested params for a data collection

This is based on Stu's proposal in the ispyb-modeling repo:
https://github.com/ispyb/ispyb-database-modeling/issues/52

### CODE REVIEW

**Comment by KarlLevik** [comment]
I'm not sure why we would need both `blSampleId` and `dataCollectionPlanId` (i.e. `diffractionPlanId`) since there is a `BlSample.diffractionPlanId` column.

**Comment by drnasmith** [comment]
Adding sampleId to this makes sense so you can queue a specific sample as well as sub samples.
Can probably do without diffractionPlanId assuming you never want to have multiple entries for the same sample and different collection plans at the same time.
Presume once collected, the diffractionPlan used can be determined from the dataCollection - rather than needing to refer to the BLSample.diffractionPlan? So whatever is currently set as the BLSample.diffractionPlan is used once the queue is read...

**Comment by stufisher** [comment]
Diffractionplan in containqueue is important, it allows us to be explicit. You could have created multiple diffractionplans for a sample (like say what we do in xpdf). Ok you have this order columns to say which order to process the plans in in blsample_has_datacollectionplan, but this is just inferred knowledge. It is much better to be explicit. It simplifies the queries to determine what has actually happened to a sample

**Comment by stufisher** [comment]
I would like to add another column to containerqueue at this point as well
```
ADD `status` VARCHAR(20) NULL DEFAULT NULL COMMENT 'The status of the queued item, i.e. skipped, reinspect. Completed / failed should be inferred from related DataCollection', 
```
There are cases where you queue a sample, something happens, but it does not result in a datacollection. Like we do on vmxi inspections, i would like to be able to make this queued entries as skipped (or maybe reinspect). Success can still be inferred from datacollection and autoprocintegration

**Comment by stufisher** [comment]
ping

**Comment by stufisher** [comment]
Superseded by https://github.com/DiamondLightSource/ispyb-database/pull/63

**Pull request closed without merging**
