### PR TITLE
Remove upsert xray centring proc

### PR DESCRIPTION
**Pull request by DominicOram**
Given that the table this procedure references is now removed the procedure should be too.

To test:
* Confirm removed procedures reference old tables that have also been removed
* Confirm no other errant places referencing the old table

### CODE REVIEW

**Comment by rjgildea** [comment]
@KarlLevik do we need an explicit ``DROP PROCEDURE IF EXISTS `upsert_xray_centring_result` `` to ensure the stored procedure gets removed from existing database instances?

**Comment by KarlLevik** [comment]
> @KarlLevik do we need an explicit `` DROP PROCEDURE IF EXISTS `upsert_xray_centring_result` `` to ensure the stored procedure gets removed from existing database instances?

Yes, that is the cleanest solution. So, we will need a .sql file in `schema/ispyb/updates/` with that statement.

Another question is whether the next version now strictly speaking ought to be 2.0.0 since this change breaks backwards compatibility in the database "API".

**Comment by rjgildea** [comment]
> Another question is whether the next version now strictly speaking ought to be 2.0.0 since this change breaks backwards compatibility in the database "API".

I guess the alternative would be to add back in the columns removed from the "legacy" version of the `XrayCentringResult` table, and leave the stored procedure in place, but mark the columns and the stored procedure as deprecated? No strong feelings either way on my part.

**Review by KarlLevik — APPROVED** [review]

**Comment by KarlLevik** [comment]
I guess the version in one sense is "just a number" so meh.

**Pull request merged**
