### PR TITLE
Add three new experimentTypes for xrf

### PR DESCRIPTION
**Pull request by stufisher**
'XRF map','Energy scan','XRF spectrum','XRF map xas'

These will overlap with the merge of EnergyScan and spectrum tables into datacollection.
XRF map xas is a combination technique collecting maps and using these to generate xas from the changing maps

### CODE REVIEW

**Comment by KarlLevik** [comment]
Sorry for slowness in reviewing this. We now have the DCG.experimentTypeId FK column and ExperimentType table, so we hope to phase out the DCG.experimentType enum. But I'm happy to add this in the interim, if you think it's still needed?

**Comment by stufisher** [comment]
Yes please. Ta!

**Comment by KarlLevik** [comment]
OK, do you mind moving the file to the new directory? Will approve if you do that.

**Comment by stufisher** [comment]
Need to check exp types based on master if more were added for scm

**Review by KarlLevik — APPROVED** [review]

**Pull request merged**
